"""update tables

Revision ID: 61db6f3867e5
Revises: 8b9245a20274
Create Date: 2023-05-10 12:18:43.259406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61db6f3867e5'
down_revision = '8b9245a20274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
