"""change to float

Revision ID: 8b9245a20274
Revises: a7c217f6c115
Create Date: 2023-04-27 11:11:28.487745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9245a20274'
down_revision = 'a7c217f6c115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_list', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
